model:
  base_learning_rate: 0.0001
  target: exps.{0}.LatentDiffusion
  params:
    # ckpt_path: stable_diffusion/models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
    # ckpt_path: checkpoints/instruct-pix2pix-00-22000.ckpt
    # ckpt_path: logs/T002-B00_2023-08-18-15-40-22/checkpoints/trainstep_checkpoints/epoch=000010-step=000034999.ckpt
    # ckpt_path: logs/T002-BB0_2023-08-19-21-06-58/checkpoints/epoch=000012.ckpt
    ckpt_path: logs/T002-B00_2023-08-18-15-40-22/checkpoints/epoch=000009.ckpt
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: edited
    cond_stage_key: edit
    image_size: 64 ### 64 <--512, 32 <-- 256, 16 <-- 128
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: true
    load_ema: false
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 0
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: exps.{0}.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: edit_dataset.HighFrequencyDataset
      params:
        path: DATASET/celeba
        split: train
        resize_res: 512
        flip_prob: 0.5
        prompt: "face, a high quality, detailed and professional image"
    validation:
      target: edit_dataset.HighFrequencyDataset
      params:
        path: DATASET/celeba
        split: val
        resize_res: 512
        prompt: "face, a high quality, detailed and professional image"
